server:
  port: 8902
spring:
  application:
    name: lyh-consumer-order-feign-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka
feign:
  hystrix:
    enabled: true
#健康监控配置
management:
  endpoint:
    health:
      show-details: always #是否健康监控显示细节
  endpoints:
    web:
      exposure:
        include: "*"
provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule