#高可用配置，三个
spring:
  application:
    name: eureka-server-ha
  profiles:
    active: peer3
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8901/eureka/,http://peer2:8902/eureka/,http://peer3:8903/eureka/
---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
server:
  port: 8901
---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
server:
  port: 8902
---
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
server:
  port: 8903